import Mathlib

namespace Smoke.CyclicGroups

variable {G : Type*} [Group G]

-- D1: basic power identities. These hold in any group/monoid and should
-- close with `group` or a single named lemma.

/-- T01: zeroth power is the identity. -/
theorem pow_zero' (a : G) : a ^ 0 = 1 := by
  exact pow_zero a

/-- T02: power adds over multiplication of exponents. -/
theorem pow_add' (a : G) (m n : ℕ) : a ^ (m + n) = a ^ m * a ^ n := by
  exact pow_add a m n

/-- T03: one to any power is one. -/
theorem one_pow' (n : ℕ) : (1 : G) ^ n = 1 := by
  exact one_pow n

/-- T04: power of a power multiplies exponents. -/
theorem pow_mul' (a : G) (m n : ℕ) : a ^ (m * n) = (a ^ m) ^ n := by
  exact pow_mul a m n

-- D2: facts about orderOf. These need the order machinery but each is a
-- single named lemma.

/-- T05: an element to its order is the identity. -/
theorem pow_orderOf' (a : G) : a ^ orderOf a = 1 := by
  exact pow_orderOf_eq_one a

/-- T06: order divides any exponent that returns the identity. -/
theorem orderOf_dvd' (a : G) (n : ℕ) (h : a ^ n = 1) : orderOf a ∣ n := by
  exact orderOf_dvd_of_pow_eq_one h

/-- T07: in a finite group, an element's order divides the group's cardinality. -/
theorem orderOf_dvd_card' [Fintype G] (a : G) : orderOf a ∣ Fintype.card G := by
  exact orderOf_dvd_card

-- D3: structural facts about cyclic groups / generated subgroups.

/-- T08: every cyclic group is abelian (commutative). -/
theorem comm_of_isCyclic [IsCyclic G] (a b : G) : a * b = b * a := by
  exact mul_comm a b

/-- T09: powers of a fixed element commute with each other. -/
theorem pow_comm (a : G) (m n : ℕ) : a ^ m * a ^ n = a ^ n * a ^ m := by
  rw [← pow_add, ← pow_add, Nat.add_comm]

/-- T10: an element of a group generated by g is some power of g. -/
theorem mem_zpowers_iff' (g a : G) :
    a ∈ Subgroup.zpowers g ↔ ∃ k : ℤ, g ^ k = a := by
  exact Subgroup.mem_zpowers_iff

end Smoke.CyclicGroups
